name: Send email to customers on iOS changelog update

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.eu-west-1.amazonaws.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_FROM }}
          reply_to: ${{ vars.EMAIL_REPLY_TO }}
          subject: ${{ vars.EMAIL_SUBJECT }}
          html_body: ${{ vars.EMAIL_BODY }}
          priority: low